### ISSUE TITLE
How can i generate a PDF with more than 1 tables?

### ISSUE THREAD

**Issue by alvmarcoux** [cedricmartel/PdfTemplate#6]
Hello. I have been using the PDFTemplateItextSharp class to generate PDFs for some time. Now i need to generate a PDF with two tables in it. 
In the page https://pdftemplate.codeplex.com/discussions/650665 i read the comment: 
> Added support for multiple tables : just add tables inside body tag, and add table data inside body data 

But can i achieve this? im not sure if could be with the one that accepts the parameters loopData and tableLoopData. 

Do you have an example XML that does this.

Thanks.

**Comment by cedricmartel** [comment]
Hi there,
Have you tried web sample project?
It is SampleItextSharp directory in repo, and it contains a sample for multiple tables, which xml file can be found here
https://github.com/cedricmartel/PdfTemplate/blob/master/SampleItextSharp/MultipleTables/test.xml
Kind regards,
