### ISSUE TITLE
Can i display an image at a fixed position?

### ISSUE THREAD

**Issue by alvmarcoux** [cedricmartel/PdfTemplate#7]
Hi. Thanks for the help with the many tables issue.

I have an XML with an image tag with fixed position inside a row tag which is inside a footer tag:
```	
<footer y="300" absolute="yes">
	<row>
		<image src="{logo}"  width="120" height="32" align="center" x="45" y="742">
			<var name="{logo}" formatter="text"  optional="no" />
		</image>
	</row>
```
with the version 1.2.1 of the PDFTemplateItextSharp this used to display the image in the specified position, calling the following overload of the method:
`public void Draw(Hashtable headerData, List<Hashtable> loopData, Hashtable bodyData, Hashtable footerData, Hashtable tableHeadData, List<Hashtable> tableLoopData, Hashtable tableFootData);`

Then, in order to show many tables in the same page, i replaced the dll for the one with the version 1.2.2 (also i had to change Moon.PDFDrawItextSharp.dll, Moon.PDFTemplate.dll and Moon.PDFDraw.dll) and used the overload:
´public void Draw(Hashtable header, Hashtable body, Hashtable footer);´

then the image wasn't shown. To show an image i have to put it in a specific row without the x and y attributes and is shown in the row, moving the other elements so i have to fixed all the xml templates with images that i have in order that they can be generated in the same way as before. 

Is there a way to display an image or other elements at a fixed position with the version 1.2.2?

**Comment by alvmarcoux** [comment]
I modified the code in PDFTemplate, PDFDrawItextSharp and PDFDraw in order to achieve this. I added the following overload to the PDFDrawItextSharp  class and to the IPDFDraw interface:
`void DrawImage(float x, float y, string src, XmlAttributeCollection imageAttrs); `
and then i changed the call to this method in the PDFTemplate.Image class:
`pdfDraw.DrawImage(absX, absY, /*src.ToString(),*/ Attributes);`
to this:
`pdfDraw.DrawImage(absX, absY, src.ToString(), Attributes);`
it seems that there was the intention to do this, considering the commented argument /*src.ToString(),*/  i dont know if could be problems with this solution that someone had already seen or if this should be commited to the main project.

**Comment by cedricmartel** [comment]
Thanks for your feedback. I will try to test these changes when I have time. 
Next time, maybe you can make a pull request with your changes ?

**Comment by cedricmartel** [comment]
I integrated your changes today
